name: Puppeteer Workflow

on:
  push:                    # ⬅️ Deploy on push
    branches:
      - main
  schedule:                # ⬅️ Run every minute automatically
    - cron: "*/1 * * * *"
  workflow_dispatch:       # ⬅️ Allow manual runs

jobs:
  puppeteer:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Install Puppeteer dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            ca-certificates \
            fonts-liberation \
            libatk-bridge2.0-0 \
            libatk1.0-0 \
            libc6 \
            libcairo2 \
            libcups2 \
            libdbus-1-3 \
            libdrm2 \
            libexpat1 \
            libfontconfig1 \
            libgbm1 \
            libgcc1 \
            libglib2.0-0 \
            libgtk-3-0 \
            libnspr4 \
            libnss3 \
            libpango-1.0-0 \
            libx11-6 \
            libx11-xcb1 \
            libxcb1 \
            libxcomposite1 \
            libxcursor1 \
            libxdamage1 \
            libxext6 \
            libxfixes3 \
            libxi6 \
            libxrandr2 \
            libxrender1 \
            libxss1 \
            libxtst6 \
            wget \
            unzip \
            xdg-utils

      - name: Run Puppeteer script
        run: node puppeteer-script.js

      - name: Generate screenshots index
        run: |
          mkdir -p public/screenshots
          cd public/screenshots
          ls *.png > index.txt || true
          node -e "const fs=require('fs'); const arr=(fs.existsSync('index.txt')?fs.readFileSync('index.txt','utf-8').split('\n').filter(Boolean):[]); fs.writeFileSync('index.json', JSON.stringify(arr,null,2));"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
