name: Puppeteer Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  puppeteer:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Install Puppeteer dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            ca-certificates \
            fonts-liberation \
            libatk-bridge2.0-0 \
            libatk1.0-0 \
            libc6 \
            libcairo2 \
            libcups2 \
            libdbus-1-3 \
            libdrm2 \
            libexpat1 \
            libfontconfig1 \
            libgbm1 \
            libgcc1 \
            libglib2.0-0 \
            libgtk-3-0 \
            libnspr4 \
            libnss3 \
            libpango-1.0-0 \
            libx11-6 \
            libx11-xcb1 \
            libxcb1 \
            libxcomposite1 \
            libxcursor1 \
            libxdamage1 \
            libxext6 \
            libxfixes3 \
            libxi6 \
            libxrandr2 \
            libxrender1 \
            libxss1 \
            libxtst6 \
            wget \
            unzip \
            xdg-utils

      - name: Run Puppeteer script
        run: node puppeteer-script.js

      - name: Generate screenshots index
        run: |
          cd public/screenshots
          ls *.png > index.txt
          node -e "const fs=require('fs'); fs.writeFileSync('index.json', JSON.stringify(fs.readFileSync('index.txt','utf-8').split('\n').filter(Boolean)))"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
           personal_token: ${{ secrets.GH_PAT }}
           publish_dir: ./public
